# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeBusinessAssistant' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeBusinessAssistant
  pod 'SQLite.swift', '~> 0.11.4'
  pod 'SwiftForms'
end
